name: trivy-scan

on:
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  trivy_scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL
          ignore-unfixed: true
          exit-code: "1"
